### ISSUE TITLE
run error under centos7 x64 

### ISSUE THREAD

**Issue by wushifeng** [sualeh/SchemaCrawler-Web-Application#1]
in "src/main/resources/application.properties" schemacrawler.webapp.storage-root is setted an absolute path in windows c:/
can change to below to avoid not find file
schemacrawler.webapp.storage-root=target/uploaded-files

and should install depend package:
yum install -y graphviz.x86_64  graphviz-java.x86_64

**Comment by sualeh** [comment]
I am not sure what you are suggesting here. Are you suggesting that that README is updated? Have you tried using the Docker image? The Docker image should work.

**Comment by wushifeng** [comment]
I run the project under centos, and has some errors described upon.
README added these information will be better
